--This file declares the contents of each floor. You can fit as many enemies as you want until the game runs out of memory
--Spawning enemies in intermission rooms will break it, I think?
--The game control will make any floor beyond 100 not matter
local floors = {}
floor_caveman = {ENT_TYPE.MONS_CAVEMAN, ENT_TYPE.MONS_CAVEMAN,ENT_TYPE.MONS_CAVEMAN,ENT_TYPE.MONS_CAVEMAN,ENT_TYPE.MONS_CAVEMAN,ENT_TYPE.MONS_CAVEMAN,ENT_TYPE.MONS_CAVEMAN,ENT_TYPE.MONS_CAVEMAN,ENT_TYPE.MONS_CAVEMAN,ENT_TYPE.MONS_CAVEMAN,ENT_TYPE.MONS_CAVEMAN,ENT_TYPE.MONS_CAVEMAN,ENT_TYPE.MONS_CAVEMAN,ENT_TYPE.MONS_CAVEMAN,ENT_TYPE.MONS_CAVEMAN,ENT_TYPE.MONS_CAVEMAN,ENT_TYPE.MONS_CAVEMAN,ENT_TYPE.MONS_CAVEMAN,ENT_TYPE.MONS_CAVEMAN,ENT_TYPE.MONS_CAVEMAN,ENT_TYPE.MONS_CAVEMAN,ENT_TYPE.MONS_CAVEMAN,ENT_TYPE.MONS_CAVEMAN,ENT_TYPE.MONS_CAVEMAN,ENT_TYPE.MONS_CAVEMAN,ENT_TYPE.MONS_CAVEMAN,ENT_TYPE.MONS_CAVEMAN,ENT_TYPE.MONS_CAVEMAN,ENT_TYPE.MONS_CAVEMAN,ENT_TYPE.MONS_CAVEMAN,ENT_TYPE.MONS_CAVEMAN,ENT_TYPE.MONS_CAVEMAN,ENT_TYPE.MONS_CAVEMAN,ENT_TYPE.MONS_CAVEMAN,ENT_TYPE.MONS_CAVEMAN,ENT_TYPE.MONS_CAVEMAN}
floors = { --IDs of enemies to spawn
    --DWELLING (1, 11)
    {ENT_TYPE.MONS_SNAKE, ENT_TYPE.MONS_SNAKE, ENT_TYPE.MONS_SNAKE, ENT_TYPE.MONS_BAT, ENT_TYPE.MONS_BAT, ENT_TYPE.MONS_BAT, ENT_TYPE.MONS_SPIDER},
    {ENT_TYPE.MONS_SNAKE, ENT_TYPE.MONS_BAT, ENT_TYPE.MONS_SNAKE, ENT_TYPE.MONS_SPIDER, ENT_TYPE.MONS_CAVEMAN, ENT_TYPE.MONS_SNAKE, ENT_TYPE.MONS_SPIDER, ENT_TYPE.MONS_CAVEMAN},
    {ENT_TYPE.MONS_SNAKE, ENT_TYPE.MONS_SNAKE, ENT_TYPE.MONS_BAT, ENT_TYPE.MONS_BAT, ENT_TYPE.MONS_SPIDER, ENT_TYPE.MONS_SCORPION},
    {ENT_TYPE.MONS_SNAKE, ENT_TYPE.MONS_SNAKE, ENT_TYPE.MONS_BAT, ENT_TYPE.MONS_SPIDER, ENT_TYPE.MONS_CAVEMAN, ENT_TYPE.MONS_HORNEDLIZARD},
    {ENT_TYPE.MONS_CAVEMAN, ENT_TYPE.MONS_CAVEMAN, ENT_TYPE.MONS_BAT, ENT_TYPE.MONS_BAT, ENT_TYPE.MONS_SPIDER, ENT_TYPE.MONS_HORNEDLIZARD, ENT_TYPE.MONS_HORNEDLIZARD, ENT_TYPE.MONS_FROG}, 
    {ENT_TYPE.MONS_SNAKE, ENT_TYPE.MONS_BAT, ENT_TYPE.MONS_SNAKE, ENT_TYPE.MONS_SPIDER, ENT_TYPE.MONS_CAVEMAN, ENT_TYPE.MONS_SNAKE, ENT_TYPE.MONS_SPIDER, ENT_TYPE.MONS_CAVEMAN, ENT_TYPE.MONS_SPIDER, ENT_TYPE.MONS_SNAKE, ENT_TYPE.MONS_SNAKE, ENT_TYPE.MONS_MOLE, ENT_TYPE.MONS_BAT},
    {ENT_TYPE.MONS_SNAKE, ENT_TYPE.MONS_BAT, ENT_TYPE.MONS_HORNEDLIZARD, ENT_TYPE.MONS_MOLE, ENT_TYPE.MONS_MOLE, ENT_TYPE.MONS_SPIDER, ENT_TYPE.MONS_MONKEY, ENT_TYPE.MONS_MOLE, ENT_TYPE.MONS_BAT}, 
    {ENT_TYPE.MONS_BAT, ENT_TYPE.MONS_BAT, ENT_TYPE.MONS_SNAKE, ENT_TYPE.MONS_SNAKE, ENT_TYPE.MONS_HORNEDLIZARD, ENT_TYPE.MONS_HORNEDLIZARD, ENT_TYPE.MONS_HORNEDLIZARD},
    {ENT_TYPE.MONS_HORNEDLIZARD, ENT_TYPE.MONS_HORNEDLIZARD, ENT_TYPE.MONS_MOLE, ENT_TYPE.MONS_CAVEMAN, ENT_TYPE.MONS_MOLE, ENT_TYPE.MONS_SNAKE, ENT_TYPE.MONS_SNAKE, ENT_TYPE.MONS_SNAKE, ENT_TYPE.MONS_SPIDER, ENT_TYPE.MONS_BAT},
    {ENT_TYPE.MONS_SNAKE, ENT_TYPE.MONS_BAT, ENT_TYPE.MONS_HORNEDLIZARD, ENT_TYPE.MONS_CAVEMAN, ENT_TYPE.MONS_MOLE, ENT_TYPE.MONS_SNAKE, ENT_TYPE.MONS_BAT, ENT_TYPE.MONS_HORNEDLIZARD, ENT_TYPE.MONS_CAVEMAN, ENT_TYPE.MONS_MOLE, ENT_TYPE.MONS_SPIDER, ENT_TYPE.MONS_SPIDER, ENT_TYPE.MONS_JIANGSHI, ENT_TYPE.MONS_JIANGSHI, ENT_TYPE.MONS_JIANGSHI},
    {}, --ENT_TYPE.MONS_CAVEMAN, ENT_TYPE.MONS_CAVEMAN_BOSS, ENT_TYPE.MONS_CAVEMAN, ENT_TYPE.MONS_CAVEMAN, ENT_TYPE.MONS_CAVEMAN, ENT_TYPE.MONS_CAVEMAN, ENT_TYPE.MONS_CAVEMAN, ENT_TYPE.MONS_CAVEMAN, ENT_TYPE.MONS_CAVEMAN, ENT_TYPE.MONS_CAVEMAN, ENT_TYPE.MONS_CAVEMAN, ENT_TYPE.MONS_CAVEMAN
    --INTERMISSION (12)
    {},
    --JUNGLE (13-24)
    {ENT_TYPE.MONS_MOSQUITO, ENT_TYPE.MONS_MONKEY, ENT_TYPE.MONS_MOSQUITO, ENT_TYPE.MONS_MONKEY, ENT_TYPE.MONS_MOSQUITO, ENT_TYPE.MONS_MONKEY, ENT_TYPE.MONS_MOSQUITO, ENT_TYPE.MONS_MONKEY},
    {ENT_TYPE.MONS_MOSQUITO, ENT_TYPE.MONS_MONKEY, ENT_TYPE.MONS_MOSQUITO, ENT_TYPE.MONS_MONKEY, ENT_TYPE.MONS_MOSQUITO, ENT_TYPE.MONS_HANGSPIDER, ENT_TYPE.MONS_HANGSPIDER, ENT_TYPE.MONS_TIKIMAN, ENT_TYPE.MONS_TIKIMAN},
    {ENT_TYPE.MONS_GIANTSPIDER, ENT_TYPE.MONS_TIKIMAN, ENT_TYPE.MONS_GIANTSPIDER, ENT_TYPE.MONS_HANGSPIDER, ENT_TYPE.MONS_HANGSPIDER, ENT_TYPE.MONS_HANGSPIDER, ENT_TYPE.MONS_CAVEMAN, ENT_TYPE.MONS_MANTRAP, MONS_HANGSPIDER, ENT_TYPE.MONS_TIKIMAN, MONS_HANGSPIDER},
    {ENT_TYPE.MONS_SPIDER, ENT_TYPE.MONS_HANGSPIDER, ENT_TYPE.MONS_WITCHDOCTOR, ENT_TYPE.MONS_GIANTSPIDER, ENT_TYPE.MONS_MOSQUITO, ENT_TYPE.MONS_HANGSPIDER, ENT_TYPE.MONS_MOSQUITO, ENT_TYPE.MONS_GIANTSPIDER},
    {ENT_TYPE.MONS_TIKIMAN, ENT_TYPE.MONS_MONKEY, ENT_TYPE.MONS_TIKIMAN, ENT_TYPE.MONS_MONKEY, ENT_TYPE.MONS_TIKIMAN, ENT_TYPE.MONS_MONKEY, ENT_TYPE.MONS_MOSQUITO, ENT_TYPE.MONS_TIKIMAN, ENT_TYPE.MONS_TIKIMAN, ENT_TYPE.MONS_MOSQUITO, ENT_TYPE.MONS_MOSQUITO},
    {ENT_TYPE.MONS_GIANTSPIDER, ENT_TYPE.MONS_MOSQUITO, ENT_TYPE.MONS_GIANTSPIDER, ENT_TYPE.MONS_HANGSPIDER, ENT_TYPE.MONS_HANGSPIDER, ENT_TYPE.MONS_HANGSPIDER, ENT_TYPE.MONS_MANTRAP, ENT_TYPE.MONS_GIANTSPIDER, ENT_TYPE.MONS_TIKIMAN, ENT_TYPE.MONS_TIKIMAN, ENT_TYPE.MONS_MANTRAP},
    {ENT_TYPE.MONS_MONKEY, ENT_TYPE.MONS_MANTRAP, ENT_TYPE.MONS_MOSQUITO, ENT_TYPE.MONS_MOSQUITO, ENT_TYPE.MONS_MOSQUITO, ENT_TYPE.MONS_MANTRAP, ENT_TYPE.MONS_MONKEY, ENT_TYPE.MONS_MONKEY},
    {ENT_TYPE.MONS_MOSQUITO, ENT_TYPE.MONS_HANGSPIDER, ENT_TYPE.MONS_HANGSPIDER, ENT_TYPE.MONS_MOSQUITO, ENT_TYPE.MONS_WITCHDOCTOR, ENT_TYPE.MONS_TIKIMAN, ENT_TYPE.MONS_CAVEMAN, ENT_TYPE.MONS_MOSQUITO, ENT_TYPE.MONS_HANGSPIDER, ENT_TYPE.MONS_HANGSPIDER},
    {ENT_TYPE.MONS_MONKEY, ENT_TYPE.MONS_MONKEY, ENT_TYPE.MONS_MONKEY, ENT_TYPE.MONS_WITCHDOCTOR, ENT_TYPE.MONS_MOSQUITO, ENT_TYPE.MONS_MOSQUITO, ENT_TYPE.MONS_WITCHDOCTOR, ENT_TYPE.MONS_WITCHDOCTOR},
    {ENT_TYPE.MONS_MANTRAP, ENT_TYPE.MONS_MANTRAP,ENT_TYPE.MONS_MANTRAP,ENT_TYPE.MONS_MANTRAP,ENT_TYPE.MONS_MANTRAP,ENT_TYPE.MONS_MANTRAP,ENT_TYPE.MONS_MANTRAP,ENT_TYPE.MONS_MANTRAP,ENT_TYPE.MONS_MANTRAP},
    {ENT_TYPE.MONS_MANTRAP, ENT_TYPE.MONS_MANTRAP,ENT_TYPE.MONS_GIANTSPIDER,ENT_TYPE.MONS_MANTRAP,ENT_TYPE.MONS_MANTRAP,ENT_TYPE.MONS_MANTRAP,ENT_TYPE.MONS_MANTRAP,ENT_TYPE.MONS_GIANTSPIDER,ENT_TYPE.MONS_MANTRAP, ENT_TYPE.MONS_WITCHDOCTOR, ENT_TYPE.MONS_WITCHDOCTOR, ENT_TYPE.MONS_WITCHDOCTOR, ENT_TYPE.MONS_MOSQUITO,ENT_TYPE.MONS_MOSQUITO,ENT_TYPE.MONS_MOSQUITO,},
    {ENT_TYPE.MONS_SHOPKEEPERCLONE, ENT_TYPE.MONS_SHOPKEEPERCLONE, ENT_TYPE.MONS_SHOPKEEPERCLONE, ENT_TYPE.MONS_SHOPKEEPERCLONE},

    --INTERMISSION (25)
    {},
    --VOLCANA (26-37)
    {ENT_TYPE.MONS_IMP, ENT_TYPE.MONS_FIREBUG, ENT_TYPE.MONS_FIREBUG, ENT_TYPE.MONS_FIREBUG, ENT_TYPE.MONS_IMP, ENT_TYPE.MONS_FIREBUG, ENT_TYPE.MONS_BAT, ENT_TYPE.MONS_BAT, ENT_TYPE.MONS_BAT},
    {ENT_TYPE.MONS_IMP, ENT_TYPE.MONS_FIREBUG, ENT_TYPE.MONS_FIREBUG_UNCHAINED, ENT_TYPE.MONS_FIREBUG_UNCHAINED, ENT_TYPE.MONS_IMP, ENT_TYPE.MONS_BAT, ENT_TYPE.MONS_ROBOT, ENT_TYPE.MONS_BAT, ENT_TYPE.MONS_BAT, ENT_TYPE.MONS_BAT, ENT_TYPE.MONS_BAT, ENT_TYPE.MONS_ROBOT, ENT_TYPE.MONS_LEPRECHAUN},
    {ENT_TYPE.MONS_BAT, ENT_TYPE.MONS_FIREBUG, ENT_TYPE.MONS_IMP, ENT_TYPE.MONS_IMP, ENT_TYPE.MONS_FIREBUG, ENT_TYPE.MONS_FIREBUG_UNCHAINED, ENT_TYPE.MONS_FIREBUG_UNCHAINED, ENT_TYPE.MONS_BAT, ENT_TYPE.MONS_BAT, ENT_TYPE.MONS_BAT, ENT_TYPE.MONS_LEPRECHAUN, ENT_TYPE.MONS_LEPRECHAUN, ENT_TYPE.MONS_LEPRECHAUN},
    {ENT_TYPE.MONS_FIREBUG, ENT_TYPE.MONS_FIREBUG_UNCHAINED, ENT_TYPE.MONS_FIREBUG, ENT_TYPE.MONS_FIREBUG_UNCHAINED, ENT_TYPE.MONS_FIREBUG, ENT_TYPE.MONS_FIREBUG_UNCHAINED, ENT_TYPE.MONS_FIREBUG, ENT_TYPE.MONS_FIREBUG_UNCHAINED, ENT_TYPE.MONS_FIREBUG, ENT_TYPE.MONS_FIREBUG_UNCHAINED, },
    {ENT_TYPE.MONS_FIREBUG, ENT_TYPE.MONS_FIREBUG_UNCHAINED, ENT_TYPE.MONS_BAT, ENT_TYPE.MONS_BAT, ENT_TYPE.MONS_BAT, ENT_TYPE.MONS_VAMPIRE, ENT_TYPE.MONS_VAMPIRE, ENT_TYPE.MONS_IMP, ENT_TYPE.MONS_IMP, ENT_TYPE.MONS_IMP, ENT_TYPE.MONS_IMP},
    {ENT_TYPE.MONS_VAMPIRE, ENT_TYPE.MONS_VAMPIRE, ENT_TYPE.MONS_VAMPIRE, ENT_TYPE.MONS_BAT, ENT_TYPE.MONS_BAT, ENT_TYPE.MONS_BAT, ENT_TYPE.MONS_IMP, ENT_TYPE.MONS_IMP, ENT_TYPE.MONS_LEPRECHAUN, ENT_TYPE.MONS_LEPRECHAUN, ENT_TYPE.MONS_IMP, ENT_TYPE.MONS_IMP, ENT_TYPE.MONS_FIREBUG},
    {ENT_TYPE.MONS_IMP, ENT_TYPE.MONS_IMP, ENT_TYPE.MONS_IMP, ENT_TYPE.MONS_IMP},
    {ENT_TYPE.MONS_IMP, ENT_TYPE.MONS_IMP, ENT_TYPE.MONS_IMP, ENT_TYPE.MONS_IMP},
    {ENT_TYPE.MONS_IMP, ENT_TYPE.MONS_IMP, ENT_TYPE.MONS_IMP, ENT_TYPE.MONS_IMP},
    {ENT_TYPE.MONS_IMP, ENT_TYPE.MONS_IMP, ENT_TYPE.MONS_IMP, ENT_TYPE.MONS_IMP},
    {ENT_TYPE.MONS_VLAD, ENT_TYPE.MONS_VAMPIRE, ENT_TYPE.MONS_VAMPIRE, ENT_TYPE.MONS_VAMPIRE, ENT_TYPE.MONS_VAMPIRE, ENT_TYPE.MONS_VAMPIRE, ENT_TYPE.MONS_VAMPIRE, ENT_TYPE.MONS_VAMPIRE, ENT_TYPE.MONS_VAMPIRE, ENT_TYPE.MONS_BAT, ENT_TYPE.MONS_BAT, ENT_TYPE.MONS_BAT},
    --OLMEC (38)
    --INTERMISSION (39)
    --TIDEPOOL (40-51)
    --INTERMISSION(52)
    --TEMPLE (53-64)
    --INTERMISSION (65)
    --ICECAVES (66-77)
    --INTERMISSION (78)
    --BABYLON (79-90)
    --INTERMISSION (91)
    --SUNKEN (92-100)
}

return floors